## Server Config
server:
  port: 8090

## Spring Config
spring:

  ## RabbitMQ Config
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    dynamic: false

## Queue Config
rabbitmq:
  exchange:
    request: ${RABBIT_EXCHANGE_REQ}
    response: ${RABBIT_EXCHANGE_RES}
  queue:
    plan-processing: ${RABBIT_QUEUE_PLAN_P}
    plan-response: ${RABBIT_QUEUE_PLAN_R}
    billing-processing: ${RABBIT_QUEUE_BILLING_P}
    billing-response: ${RABBIT_QUEUE_BILLING_R}
  routing-key:
    plan-processing: ${RABBIT_RK_PLAN_P}
    plan-response: ${RABBIT_RK_PLAN_R}
    billing-processing: ${RABBIT_RK_BILLING_P}
    billing-response: ${RABBIT_RK_BILLING_R}

## PDF Billing Config
billing:
  resources:
    paths:
      img:
        logo: ${BILLING_LOGO}
        qr: ${BILLING_QR}
      pdf:
        template: ${BILLING_TEMPLATE}
        save-folder: ${BILLING_FOLDER}

## Mail Config
mail:
  properties:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    smtp:
      auth: ${MAIL_SMTP_AUTH}
      start-tls: ${MAIL_SMTP_START_TLS}
      host: ${MAIL_HOST}
      port: ${MAIL_CONTENT_PORT}
  message:
    content:
      file:
        pdf: ${MAIL_PDF_NAME}